### ISSUE TITLE
[BUG] Issue with EventEmitter type definition

### ISSUE THREAD

**Issue by philipp-schmidt** [open-feature/js-sdk#1035]
### Observed behavior

tsc output:
```
node_modules/.pnpm/@openfeature+server-sdk@1.15.1_@openfeature+core@1.4.0/node_modules/@openfeature/server-sdk/dist/types.d.ts(212,38): error TS2315: Type 'EventEmitter' is not generic.
6.597  ELIFECYCLE  Command failed with exit code 2.
```

Comes from type definition here:

```
import { EventEmitter } from 'node:events';

...

/**
 * The OpenFeatureEventEmitter can be used by provider developers to emit
 * events at various parts of the provider lifecycle.
 *
 * NOTE: Ready and error events are automatically emitted by the SDK based on
 * the result of the initialize method.
 */
declare class OpenFeatureEventEmitter extends GenericEventEmitter<ServerProviderEvents> {
    protected readonly eventEmitter: EventEmitter<[never]>;
    constructor();
}
```

nodejs 18

Anyone knows what the issue here? Is node 18 not supported anymore?

**Comment by beeme1mr** [comment]
Hi @philipp-schmidt, could you please provide a minimal reproduction? There's likely an issue with a specific dependency version or in the TS config.

**Comment by philipp-schmidt** [comment]
Hi, thanks for the quick response. I haven't checked if and how it is related to my tsconfig, that's possible. Will check and update here.

**Comment by beeme1mr** [comment]
It should work with node 18. I quickly checked the code again. We're not explicitly passing a generic to the EventEmitter. This must happen during compilation.

What version of TypeScript are you using? It looks like TypeScript added generics to the EventEmitter type in version 3.7.

**Comment by philipp-schmidt** [comment]
Yep, happens during compilation. typescript is 5.2.2, I don't think that's the issue.

I'm working on a reproducible example. Will probably spot the issue when setting this up more minimally.

**Comment by philipp-schmidt** [comment]
Hi, the issue was fixed by installing the node types

`pnpm i -D @types/node`

It is very likely this is due to my specific project setup and does not affect other users.

Thanks for the help @beeme1mr !
