### ISSUE TITLE
[FEATURE] angular-sdk: Add Angular v19 support

### ISSUE THREAD

**Issue by adamlwomble** [open-feature/js-sdk#1083]
### Requirements

At present, attempting to install the Angular SDK in an Angular v19 project results in an error because the SDK is dependent on older versions of Angular.

**Comment by beeme1mr** [comment]
Hey @lukas-reining, could you please take a look when you have a moment?

**Comment by lukas-reining** [comment]
Hey @adamlwomble,thanks I did not see Angular 19 being released yesterday.
I will test the SDK with Angular 19 tomorrow and then open a PR to add Angular 19 to the peerDeps.
If you need it to work directly you can set [https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides) in your package.json.

**Comment by lukas-reining** [comment]
It works for me in a test App and the test run so we can support Angular 19 :) 
Opened the PR here: #1084
Thanks for bringing it up @adamlwomble

**Comment by lukas-reining** [comment]
A new version that supports Angular 19 is published now @adamlwomble :)
https://www.npmjs.com/package/@openfeature/angular-sdk/v/0.0.9-experimental

Thanks for opening the issue and I hope it works as expected!

**Comment by adamlwomble** [comment]
Thank you for the prompt attention and update!
