### ISSUE TITLE
[BUG] Typescript doesn't find the included types

### ISSUE THREAD

**Issue by talzion12** [open-feature/js-sdk#354]
### Observed behavior

I tried to import OpenFeature in a Typescript project but encountered the following error:
`Could not find a declaration file for module '@openfeature/js-sdk'. '.../node_modules/@openfeature/js-sdk/dist/esm/index.js' implicitly has an 'any' type.`.

Editing openfeature's `package.json` so that it references the types from the exports section resolves the problem:
```json
"exports": {
  "import": "./dist/esm/index.js",
  "require": "./dist/cjs/index.js",
  "default": "./dist/cjs/index.js",
  "types": "./dist/types/index.d.ts"
},
```

### Expected Behavior

Typescript should find the included types.

### Steps to reproduce

Create a Typescript project and try to import `@openfeature/js-sdk`.

Typescript version: 4.9.4.
Node version: 16.18.1.

tsconfig:
```json
{
  "compilerOptions": {
    "outDir": "build",
    "target": "ES2022",
    "strict": true,
    "module": "Node16"
  }
}
```

**Comment by beeme1mr** [comment]
Hi @talzion12, thanks for reporting this issue. We'll look into it today.

**Comment by toddbaert** [comment]
@talzion12 https://github.com/open-feature/js-sdk/pull/355#pullrequestreview-1229313447 an unfortunate issue. Thanks for reporting.
