### ISSUE TITLE
[testing] create integration tests for web-sdk

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#376]
We should create a cucumber suite for the web-sdk (similar to that in the js-sdk) that runs in a simulated browser environment. We may want to wait until the spec PR is merged or more stable, but we should have some tests sooner than later.

**Comment by mowies** [comment]
Hey @toddbaert ! I'd like to work on this, but I think I need some guidance on what to how to test. I already started a branch in my fork with some base setup things like adding a new npm run command for the client integration tests.
You can find the draft PR here: #400

**Comment by toddbaert** [comment]
We'll meet next week as discussed on slack.
