### ISSUE TITLE
[web-sdk] Add tests for initialization/shutdown

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#406]
The web-sdk implements initialization and shutdown as per this [spec PR](https://github.com/open-feature/spec/pull/179) and this [OFEP](https://github.com/open-feature/ofep/pull/46).

We've implemented the tests equivalent to the server SDK [here](https://github.com/open-feature/js-sdk/commit/39f64742cf308bb83a4299b069d61f6ebfac9a46), but because the init/shutdown features don't exist in the server yet, we need to implement them in the web SDK.

Primarily, we want to cover the init/shutdown logic in the [`setProvider` method](https://github.com/open-feature/js-sdk/blob/main/packages/client/src/open-feature.ts#L86-L112), and in the [`close` method](https://github.com/open-feature/js-sdk/blob/main/packages/client/src/open-feature.ts#L114-L116).

DoD:

- test(s) that assert shutdown is called on the old provider when a new one is set
- test(s) that assert initialize is called on the new provider
- test(s) that assert shutdown is called on the provider when the `close()` method on the API is called
- tests are numbered/named in accordance with [spec PR](https://github.com/open-feature/spec/pull/179)

**Comment by RealAnna** [comment]
starting this :)
