### ISSUE TITLE
[web-sdk] Add tests for events

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#407]
The web-sdk implements events as per this [spec PR]([specification/sections/05-events.md](https://github.com/open-feature/spec/pull/171) (see specification/sections/05-events.md). 
We've implemented the tests equivalent to the server SDK [here](https://github.com/open-feature/js-sdk/commit/39f64742cf308bb83a4299b069d61f6ebfac9a46), but because the events features don't exist in the server yet, we need to implement them in the web SDK fresh.

Primarily, we want to cover the event logic.

DoD:

- test(s) that assert when the provider is initialized (the initialize promise resolves) the READY event fires on a registered client
- test(s) that assert when the provider initialization fails (the initialize promise rejects) the ERROR event fires on a registered client
- test(s) that assert when a provider fires the CONFIGURATION_CHANGED event, the event fires on a registered client
- other reasonable assertions based on the draft spec PR.

**Comment by RealAnna** [comment]
I can try these!
