### ISSUE TITLE
[tests] Use scoped providers for testing when implemented

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#421]
When [provider mapping](https://github.com/open-feature/spec/pull/183) is implemented, we can scope providers to prevent tests from trampling on each other.

Each test should register a provider with a name, preventing tests from failing due to interference.

**Comment by beeme1mr** [comment]
Depends on https://github.com/open-feature/js-sdk/issues/428

**Comment by lukas-reining** [comment]
Should be done by #429 right? @beeme1mr @toddbaert

**Comment by toddbaert** [comment]
Maybe? I'll double check. There may be a few things that need updating. If not I will close.

**Comment by toddbaert** [comment]
This is done
