### ISSUE TITLE
Changes to support spec `v0.6.0` compliance

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#424]
## Implement specification v0.6.0 changes

See [changes since last release](https://github.com/open-feature/spec/compare/v0.5.2...v0.6.0).

Please note there's no need to complete all these tasks in a single PR (in fact, that's not recommended).

### Functional requirements:

- [x] #425
- [x] #428
- [x] implement initialization/shutdown: https://github.com/open-feature/spec/commit/a4ffec3d4416b8ad6d12d1ebfa2faf81ad153f65
- [x] implement events: https://github.com/open-feature/spec/commit/bf9e45b1d51c316ee2d6340bc2b807294995d0ad

### Non-functional requirements:

- [x] common types/code implemented in `packages/shared`
  - :mega:  **_much is already implemented in `packages/client` and will need to be moved to `packages/shared`_** :mega: 
- [x] add relevant tests
- [x] #440
- [x] update specification badge to `v0.6.0`: [![Specification](https://img.shields.io/static/v1?label=Specification&message=v0.6.0&color=yellow)](https://github.com/open-feature/spec/tree/v0.6.0)

### Keep in mind:

- backwards compatibility is _highly encouraged_
  - take every precaution to ensure existing code written by _application authors_ and existing providers implementations, do not break
- it's recommended these features are released together

**Comment by lukas-reining** [comment]
As said I could work on this @toddbaert 🙂

**Comment by toddbaert** [comment]
@lukas-reining @beeme1mr WRT events, I'm wondering whether or not we should expose events on the client using the OpenFeatureEventEmitter (which is basically a node EventEmitter) or not...

So basically... should we do a custom method:

client.addhandler(ProviderEvent, handlerFn)

or just leverage native events:

client.events.on(ProviderEvent, handlerFn)

**Comment by lukas-reining** [comment]
@toddbaert I would say having  the `OpenFeatureEventEmitter` and also exposing it from the client makes sense.

But instead of just aliasing it, I would make this an interface that we can implement.
Having the class OpenFeatureEventEmitter and specifying exactly what we need e.g. `client.addHandler(ProviderEvent, handlerFn)` would decouple us from NodeEventEmitter.
This could make it easier to test and also enables us to define exactly what we need for the interface instead of having all the functionality of `NodeEventEmitter` leak through.

> Each have their own benefits. We have full control over a custom implementation, but on the other hand the EventEmitter route gives us a lot for free (once, removal, etc)

I think for the moment `OpenFeatureEventEmitter` could just be a thin wrapper so that we still get all the features that we need basically for free.

**Comment by lukas-reining** [comment]
I would first start to work on the named client support now.
This is mostly copying from the client right @toddbaert?

**Comment by lukas-reining** [comment]
@toddbaert @beeme1mr In both the web and node SDK, the function for getting a client has a version `getClient(name?: string, version?: string,...)`.
We do not have this specified and it is not that straightforward to implement the `setProvider(provider: Provider)` function now. Do we want to use the version here too? 

Does this comply to `Requirement 1.1.3` which states the following? 
>The `API` MUST provide a function to bind a given `provider` to one or more client `name`s. If the client-name already has a bound provider, it is overwritten with the new mapping.

The function could look something like this `setProvider(provider: Provider, ...clients: string[])`, but this does not include the version.

**Comment by lukas-reining** [comment]
I am working on events and init/shutdown now 🙂

**Comment by lukas-reining** [comment]
@toddbaert should we close this?

**Comment by toddbaert** [comment]
@lukas-reining Possibly. I've been working on the Java events impl though and I think I've seen that we might need a few minor (non-breaking) changes. I will circle back on that.

**Comment by toddbaert** [comment]
@lukas-reining I opened [this](https://github.com/open-feature/js-sdk/pull/461). I think it's enough for tracking the last changes we need. I'm closing this issue. Thanks for all your contributions.
