### ISSUE TITLE
implement named client support: open-feature/spec@4cf8229

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/js-sdk#428]
Add named client support to the JS SDK based on the recent update to the spec: https://github.com/open-feature/spec/commit/4cf8229d23a88feeaadf8b066e5d3662b94ff262

This feature has already been implemented in Java. It can be used as a reference for the JS implementation.
https://github.com/open-feature/java-sdk/pull/388

**Comment by lukas-reining** [comment]
But wouldn't this be a problem because of the breaking change?
If I get it right, this would remove the version from it, so current implementations would be broken.

**Comment by beeme1mr** [comment]
I talked to @lukas-reining about overloading the method and documenting the purpose of each property. The client's name will have meaning after this chance, but only if the name matches a registered provider. The version remains purely informational and doesn't affect runtime behavior.

The overload could look something like this.

```ts
getClient(context?: EvaluationContext)
getClient(name: string, context?: EvaluationContext)
getClient(name: string, version: string, context?: EvaluationContext)
getClient(nameOrContext?: string | EvaluationContext, VersionOrContext?: string | EvaluationContext, context?: EvaluationContext)
```

**Comment by toddbaert** [comment]
> I talked to @lukas-reining about overloading the method and documenting the purpose of each property. The client's name will have meaning after this chance, but only if the name matches a registered provider. The version remains purely informational and doesn't affect runtime behavior.
> 
> The overload could look something like this.
> 
> ```ts
> getClient(context?: EvaluationContext)
> getClient(name: string, context?: EvaluationContext)
> getClient(name: string, version: string, context?: EvaluationContext)
> getClient(nameOrContext?: string | EvaluationContext, VersionOrContext?: string | EvaluationContext, context?: EvaluationContext)
> ```

This all sounds right to me.
