### ISSUE TITLE
web-sdk: onContextChange not called for named provider

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/js-sdk#488]
### Observed behavior
I am not sure to understand how do you change the context for a named provider?

Let's say I am doing something like this :
```javascript
await OpenFeature.setContext({targetingKey: 'foo'});
OpenFeature.setProvider('my-provider', provider);
const client = await OpenFeature.getClient('my-provider');
//...
await OpenFeature.setContext({targetingKey: 'bar'});
```

### Expected Behavior
I was expecting the function `onContextChange` of the provider to be called when changing the context.
But when looking at the code https://github.com/open-feature/js-sdk/blob/5725194393329cb65cf82a7a76c4ed2bd5d7bcf0/packages/client/src/open-feature.ts#L37-L41

 it seems that this function is called only for the default provider.

Is it something expected? Did I miss something to be sure that `onContextChange` is call on the provider.

**Comment by beeme1mr** [comment]
Hey @thomaspoignant, I would also expect the SDK to call `onContextChange` on all registered providers. Looking at the code, it looks like an error would bubble up to the user if the context change method throws in a provider. Is that the functionality we want? @toddbaert, what do you think?

**Comment by toddbaert** [comment]
Ya I agree this is a bug. Context is global in the static context, that's a clear case. I think this is just a bug that we missed when implementing the js-sdk.

**Comment by beeme1mr** [comment]
Hey @lukas-reining, yes, it should cover the static context change. That spec change should be merged today 😄

**Comment by lukas-reining** [comment]
> Looking at the code, it looks like an error would bubble up to the user if the context change method throws in a provider. Is that the functionality we want? @toddbaert, what do you think?

What do we do about this? @beeme1mr
