### ISSUE TITLE
web-sdk: clientName in EventDetails is overriden

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/js-sdk#489]
### Observed behavior
When writing a provider for the web-sdk, you can emit events and it is possible to provide `EventDetails` with the event.

```javascript
const events = new OpenFeatureEventEmitter();
events.emit(ProviderEvents.Error, {
    clientName: 'my-client-name',
    message: 'your message here'
});
```

When reading the event, from the handler we can see that the value of the client name is not what was provided in the event.

```javascript
await OpenFeature.setContext(defaultContext);
OpenFeature.setProvider('test-provider', defaultProvider);
const client = await OpenFeature.getClient('test-provider');
client.addHandler(ProviderEvents.Error, (event) => console.log(event));

// Result:
//{
//  clientName: 'test-provider',
//  message: 'Request failed with status code 404'
//}
```
The value of `clientName` is the client's name set in `setProvider` or `undefined` if we have no name for the provider.

### Expected Behavior
Not sure exactly how it should work here, but I see 2 potential solutions:
1. Don't expose `clientName` to providers to avoid confusion for people writing providers.
2. Use the `clientName` provided in the `emit` function and forward it in the event.

**Comment by beeme1mr** [comment]
Hey @thomaspoignant, I think option 1 makes the most sense. The actual behavior seems to work how I would expect.

I'll take a shot at addressing this.

**Comment by thomaspoignant** [comment]
Yes, I agree for me option 1 is probably the best one.
