### ISSUE TITLE
[BUG] client and server SDKs both initialize providers regardless of `status`.

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#505]
The SDKs currently initialize providers regardless of their state. This can mean providers could be initialized multiple times in some situations.

The spec could be a bit more strongly worded about this, but I think [1.1.2.2](https://openfeature.dev/specification/sections/flag-evaluation#requirement-1122) makes it clear (see also linked provider section).

I think we should fix this. We could also perhaps add some type guards to make this easier (for instance, force implementation of `status` if you also implement `OpenFeatureEventEmitter` since if you support events you probably need to define `initialize` and `status`.

Note both the [Java](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/ProviderRepository.java#L107-L108) and [Go](https://github.com/open-feature/go-sdk/blob/main/pkg/openfeature/api.go#L173) impls do not have this issue; they only initialize `NOT_READY` providers.

_I will happily take this issue on, I just want to me sure everyone agrees and is aware._

**Comment by toddbaert** [comment]
I will happily take this issue on, I just want to me sure everyone agrees and is aware.

**Comment by lukas-reining** [comment]
@toddbaert Yeah, thats true. 
If you dont find the time, I can also do it. If so, just reach out 🙂

**Comment by toddbaert** [comment]
@lukas-reining I've fixed the issue, but we probably want to fix these before we release this:

- https://github.com/open-feature/js-sdk-contrib/issues/488
- https://github.com/open-feature/js-sdk-contrib/issues/489 
- https://github.com/open-feature/js-sdk-contrib/issues/490 for these.

**Comment by lukas-reining** [comment]
Okay, I will fix this for config cat now. @toddbaert
