### ISSUE TITLE
[DOC] improve web-sdk docs

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#570]
### Change in the documentation

The web docs are a bit out of date, and missing important info:

- provider example should include "onContextChanged" handler
- specially mention that context is global and setting it is `async`
- review doc carefully to find other missing examples

**Comment by luizgribeiro** [comment]
I'd like to work on this, but I was trying to set up a local  example of web client using the `InMemoryProvider` and it does not seem to be suitable for this. When I tried to configure it as the default provider the following error was given:

```
Uncaught TypeError: import_events.default is not a constructor
    GenericEventEmitter open-feature-event-emitter.ts:11
    InternalEventEmitter open-feature-event-emitter.ts:83
    OpenFeatureCommonAPI open-feature.ts:30
    OpenFeatureAPI open-feature.ts:24
    getInstance open-feature.ts:38
    <anonymous> open-feature.ts:113
```
Is there any provider that currently works for the web?

**Comment by toddbaert** [comment]
@luizgribeiro You're right.... that provider was only built to support the server.

There's also [this issue](https://github.com/open-feature/js-sdk/issues/565), which is to actually create an in-memory provider as part of the SDK, if you're interested in implementing that first, which might help in doing this task.

There are a couple web-sdk providers though if you'd like to just work on this doc issue:

- go-feature-flag-web: https://github.com/open-feature/js-sdk-contrib/tree/main/libs/providers/go-feature-flag-web
- flagd-web: https://github.com/open-feature/js-sdk-contrib/tree/main/libs/providers/go-feature-flag-web

**Comment by luizgribeiro** [comment]
I've just managed to get flagd-web + js-web sdk working here.
Even though I think that the in-memory provider is more interesting than this one I prefer to make something smaller first. Can you assign this issue to me please?

About the docs do you think it's worth mentioning in js-web which providers are currently supported?

**Comment by toddbaert** [comment]
> I've just managed to get flagd-web + js-web sdk working here. Even though I think that the in-memory provider is more interesting than this one I prefer to make something smaller first. Can you assign this issue to me please?

Understood, assigned, and thank you!
 
> About the docs do you think it's worth mentioning in js-web which providers are currently supported?

We have a full catalog of providers (and other stuff) [here](https://openfeature.dev/ecosystem), and you can filter on client/server, so I don't think we need to document it here as well.

**Comment by luizgribeiro** [comment]
Before diving a bit deeper in this, I have a question.

 You mention `onContextChanged` but I couldn't find it  in flagd-web provider or in the spec. Is there any other doc that I could use as reference? What I found on flagd-web was `onContextChange`, which by the name I'd say it gets a callback (like onClick, onHover) but the signature looked like this:
```
onContextChange(oldContext: EvaluationContext, newContext: EvaluationContext): Promise<void>;
``` 

After testing it out I discovered that it sends a request to flagd and gets the flags specs with the new context. Is this the feature that should be documented or something else?

**Comment by juanparadox** [comment]
@luizgribeiro Did you by any chance find a way to fix the constructor error you posted? I'm trying to import the client launch darkly library and am getting the same issue. I'm not even invoking it, just importing it.

**Comment by toddbaert** [comment]
> @luizgribeiro Did you by any chance find a way to fix the constructor error you posted? I'm trying to import the client launch darkly library and am getting the same issue. I'm not even invoking it, just importing it.

Hey @juanparadox . In @luizgribeiro , the issue was mixing a _server_ provider with the _web_ SDK (these are not compatible). You might want to double check that your components are all meant for the same runtime environment. If you check that and you're still having trouble, please open a new issue, listing all the components you're using, and their versions.

**Comment by juanparadox** [comment]
@toddbaert Thank you for the prompt response. I was trying to use [this](https://github.com/open-feature/js-sdk-contrib/tree/main/libs/providers/launchdarkly-client) client provider with the web sdk (`@openfeature/web-sdk`) and it's giving the same constructor error when simply importing:

`import { LaunchDarklyClientProvider } from "@openfeature/launchdarkly-client-provider";`

Sounds like it might be worthy of me opening a new issue so I'll go ahead and do that unless that client provider is actually a server provider for some reason?

**Comment by toddbaert** [comment]
> @toddbaert Thank you for the prompt response. I was trying to use [this](https://github.com/open-feature/js-sdk-contrib/tree/main/libs/providers/launchdarkly-client) client provider with the web sdk (`@openfeature/web-sdk`) and it's giving the same constructor error when simply importing:
> 
> `import { LaunchDarklyClientProvider } from "@openfeature/launchdarkly-client-provider";`

Thanks for clarifying.

> Sounds like it might be worthy of me opening a new issue so I'll go ahead and do that unless that client provider is actually a server provider for some reason?

Yes, that would be helpful. Please ping me in the issue.

**Comment by juanparadox** [comment]
@toddbaert Thanks, just created it and left a comment pinging you.
