### ISSUE TITLE
[proposal] rename @openfeature/js-sdk to @openfeature/server-sdk

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#575]
As came up in the last community meeting, `@openfeauter/js-sdk` is somewhat vague. We've heard of a few cases were a lot of time is wasted because devs import it in a client side web-app instead of `@openfeature/web-sdk`.

I propose we rename the package `@openfeature/server-sdk`. Reasoning:

- `server-sdk` makes clear it's not for web
- `server-sdk` doesn't restrict runtime to just node (deno/bun could be used)
- "JS" is redundant, and implied with npm/yarn.

We can publish a final version of the `@openfeaature/js-sdk` with a readme pointing to this new artifact, and a deprecation notice, and then deprecate the package.

EDIT: We can also decide _not_ to do this!

---

CONCLUSION:

It seems like there's a consensus for `server-sdk`.
I will push a final version of the @openfeature/js-sdk, with an updated readme referencing the new location.

**Comment by justinabrahms** [comment]
I would prefer we don't name it `server-sdk` without putting javascript in there somewhere like `js-server-sdk`. `nodejs-sdk` would fit the bill, in my mind. I would guess (though I don't know) that deno/bun developers think "Oh, it says nodejs. It'll probably work for me", rather than "Oh, nodejs? That's definitely not going to work w/ deno/bun".

All of that said, maybe I'm actually resistant to the mismatch between github.com/open-feature/js-sdk and `@openfeature/server-sdk` ? I agree that as long as it's within the context of npm/yarn, it is much clearer.

**Comment by liran2000** [comment]
In my opinion, something like _js-server-sdk_ make it more clear that it is _js_ SDK. Otherwise it may imply that this is the main server sdk, where it is similar to _go-sdk_, _java-sdk_ etc'.

**Comment by thomaspoignant** [comment]
Agree with others here `@openfeature/js-server-sdk` and `@openfeature/web-sdk` would be better.
That being said it will probably cause breaking changes to the people already using it. 
Do we want to deprecate directly? or should we continue to deploy the package in the 2 names for some times?

**Comment by tcarrio** [comment]
Putting the language in the name of a package that supports only that language is redundant. I would prefer we remove "JS" from the npm package name.

For the GitHub repository, "JS" in the name _does_ make sense.

|GitHub|NPM|
|-|-|
|js-web-sdk|@openfeature/web-sdk|
|js-server-sdk|@openfeature/server-sdk|

We can defer changes to the Web repo for now, but that seems like the most consistent for source repository naming and their related JS packages.

**Comment by toddbaert** [comment]
@tcarrio You've basically expressed my thoughts, with the small note that `https://github.com/open-feature/js-sdk` contains both the web and server artifacts (it's a monorepo).

**Comment by toddbaert** [comment]
> I would prefer we don't name it `server-sdk` without putting javascript in there somewhere like `js-server-sdk`. `nodejs-sdk` would fit the bill, in my mind. I would guess (though I don't know) that deno/bun developers think "Oh, it says nodejs. It'll probably work for me", rather than "Oh, nodejs? That's definitely not going to work w/ deno/bun".
> 
> All of that said, maybe I'm actually resistant to the mismatch between github.com/open-feature/js-sdk and `@openfeature/server-sdk` ? I agree that as long as it's within the context of npm/yarn, it is much clearer.

@justinabrahms 

I agree that bun/deno people probably won't be put off by node, so I could also be sold on `node-sdk`. A lot of node-js packages are named something like `node-xyz`, for example: https://www.npmjs.com/package/node-cache. I could also be sold on `nodejs-sdk`, but I think I'd prefer either `server-sdk` or `node-sdk`.

**Comment by lukas-reining** [comment]
Personally I would go with `server-sdk`. I do not see a reason to frame the naming by node, and js seems redundant to me.
Also I support the rename, as `js-sdk` can be really confusing to people not too much into the project.

**Comment by moredip** [comment]
+1 on the rename, +1 on `server-sdk` (although I think `node-sdk` would also be fine).

In an ideal world we'd also travel back in time and rename `web-sdk` to `browser-sdk`, but I'm not sure it's worth the hassle of renaming that at this point.

**Comment by toddbaert** [comment]
This is completed. The [new package](https://www.npmjs.com/package/@openfeature/server-sdk) is available. The [old is deprecated](https://www.npmjs.com/package/@openfeature/js-sdk) with a custom notice pointing to the new one, which appears on the web, and in console when it's installed. All impacted components in the contib repos have be released with the new peer.

**Comment by toddbaert** [comment]
I've opened a PR for a quick blog about this: https://github.com/open-feature/openfeature.dev/pull/255
