### ISSUE TITLE
[BUG] Importing the @openfeature/launchdarkly-client-provider throws a TypeError

### ISSUE THREAD

**Issue by juanparadox** [open-feature/js-sdk#659]
### Observed behavior

I installed the `@openfeature/web-sdk` and `@openfeature/launchdarkly-client-provider` packages using `pnpm install`. 

Upon trying to simply import the `LaunchDarklyClientProvider` via `import { LaunchDarklyClientProvider } from "@openfeature/launchdarkly-client-provider";` and running my local app (it's the boilerplate Vite React project that the Vite install provides) a TypeError.

```
open-feature-event-emitter.ts:11 Uncaught TypeError: import_events.default is not a constructor
    at new GenericEventEmitter (open-feature-event-emitter.ts:11:35)
    at new InternalEventEmitter (open-feature-event-emitter.ts:83:8)
    at new OpenFeatureCommonAPI (open-feature.ts:21:30)
    at new OpenFeatureAPI (open-feature.ts:18:5)
    at OpenFeatureAPI.getInstance (open-feature.ts:32:22)
    at open-feature.ts:92:43
```

### Expected Behavior

I expected the provider to be able to be imported without a `TypeError` being thrown so that it can be instantiated into the `OpenFeature.setProvider` method.

### Steps to reproduce

1. Install the `@openfeature/web-sdk` library (This may not be necessary as the issue occurs when just importing the provider library below)
2. Install the `@openfeature/launchdarkly-client-provider` library
3. Create a new file, say `featureFlags.ts` with the following (this is as bare of code you can write to reproduce the issue, I understand it's not creating a LaunchDarklyClientProvider instance or doing anything with the import, you could skip this step and just import the provider library directly into a file your app is already using)

```
import { LaunchDarklyClientProvider } from "@openfeature/launchdarkly-client-provider";
```

4. Import that file into your app, something like

```
import './featureFlags';
```
5. TypeError is thrown upon running the application

**Comment by juanparadox** [comment]
@toddbaert Just created the issue about the constructor error. Please let me know if you need more details.

**Comment by toddbaert** [comment]
Thanks @juanparadox . Can you confirm the versions you're using (I'm assuming both @ latest)?

And are you using yarn or npm? (They behave a bit differently with peer dependencies, which may be related to the problem).

**Comment by juanparadox** [comment]
@toddbaert Yeah! They are both at the latest versions and I am using pnpm.

**Comment by toddbaert** [comment]
> @toddbaert Yeah! They are both at the latest versions and I am using pnpm.

I believe pnpm doesn't [automatically install peer dependencies](https://pnpm.io/next/npmrc#:~:text=auto%2Dinstall%2Dpeers%E2%80%8B&text=When%20true%20%2C%20any%20missing%20non,peer%20dependencies%20are%20automatically%20installed). Can you confirm `@openfeature/core` is installed?

**Comment by juanparadox** [comment]
@toddbaert I just manually installed `@openfeature/core` with pnpm and the error still occurs.

**Comment by toddbaert** [comment]
> @toddbaert I just manually installed `@openfeature/core` with pnpm and the error still occurs.

Ok thanks again! I'll try to replicate the issue myself and get back to you 🙏

**Comment by juanparadox** [comment]
Thank you very much!

**Comment by toddbaert** [comment]
@juanparadox fix is released. Please let me know if your problem is resolved.

**Comment by juanparadox** [comment]
@toddbaert Fix looks to have worked! Thank you!
