### ISSUE TITLE
[BUG] typings don't support returning Promise<void>

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#689]
### Observed behavior

It looks like we have an error with the typings for the hooks when it comes to returning a `Promise<void>` from the server-sdk:

![image](https://github.com/open-feature/js-sdk/assets/25272906/5343e824-c3e9-49fa-bb9f-bedbfdfcc36d)

'Promise<void>' is not assignable to type 'Promise<EvaluationContext>' is the error.

I think the problem is [here](https://github.com/open-feature/js-sdk/blob/cc9fe79c556365d9cd6542d9c443a14166de4e08/packages/server/src/hooks/hook.ts#L5). We have `Promise<EvaluationContext | Promise<void>>`. I think this should read: `Promise<EvaluationContext> | Promise<void>` instead, or I'm missing something.

cc @beeme1mr @lukas-reining

**Comment by beeme1mr** [comment]
Yes, It looks like the current type is expecting a nested promise.

**Comment by lukas-reining** [comment]
Ah that's a typo 🤦‍♂️
