### ISSUE TITLE
Use in-memory provider for e2e suites

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#712]
Currently, we use flagd for e2e testing in this repo (see following links). Now that we have in-memory providers for both web and server, we should remove the dependency on flagd and use the in-memory providers for these gherkin suites.

Remove this file: https://github.com/open-feature/js-sdk/blob/main/packages/server/e2e/step-definitions/setup.ts and this file: https://github.com/open-feature/js-sdk/blob/main/packages/client/e2e/step-definitions/setup.ts and configure the in-memory provider in the evaluation.spec gherkin implementations themselves ([here](https://github.com/open-feature/js-sdk/blob/a3799e1b658bafca5ea11528399e7560ef43d3e6/packages/server/e2e/step-definitions/evaluation.spec.ts#L22) and [here](https://github.com/open-feature/js-sdk/blob/a3799e1b658bafca5ea11528399e7560ef43d3e6/packages/client/e2e/step-definitions/evaluation.spec.ts#L20)).

**Comment by znonthedev** [comment]
Raised a PR for the above. Please review
