### ISSUE TITLE
Support promises in Web SDK  

### ISSUE THREAD

**Issue by Nikzz3** [open-feature/js-sdk#822]
We should develop a Provider for the Web SDK. We are using [grpc](https://grpc.io/) to send a request to the Flag management system.

The grpc request is asynchronious and has to be used like this:
```ts
const response: Promise<any> = this.client.boolEvaluation(request, {});
```
According to the Web SDK documentation you have to implement this structure (return type is relevant here):
```ts
class MyProvider implements Provider {
  resolveBooleanEvaluation(flagKey: string, defaultValue: boolean, context: EvaluationContext, logger: Logger): ResolutionDetails<boolean> {
    // code to evaluate a boolean
  }
}
```
The important part is the return type which is not a promise. Why is that?

In the Node.js version it is using a promise. (see [here](https://openfeature.dev/docs/reference/technologies/server/javascript/#develop-a-provider))

According to the documenation of the Web SDK you are supposed to get all Features Flags at the beginning and therefore the flag evaluation process is synchronous. This solution doesn't really work with for us. (More information can be found [here](https://openfeature.dev/docs/reference/technologies/client/web#flag-evaluation-flow))

My question:
Why can't the resolveBooleanEvaluation method support a Promise as a return type?

**Comment by beeme1mr** [comment]
Hi @Nikzz3, the web SDK conforms to the [static context paradigm](https://openfeature.dev/specification/glossary#sdk-paradigms). The idea is that context tends to be relatively static on the client and only changes when noteworthy events occur, like the page being initially loaded or a user logging in. We can use this to improve performance by either bulk evaluating all the relative flags or fetching a ruleset locally. You can read more about those techniques [here](https://openfeature.dev/blog/catering-to-the-client-side).

The web SDK shares a significant amount of logic with the server SDK. However, as you noted, the evaluation APIs vary slightly. Not only does it not support promises, but you can't pass context per evaluation. We did this to support as many existing tools and vendors as possible while minimizing the performance impact on an app.

Would it be possible to add a bulk evaluation API to your flag management system? We're also in the process of defining a [remote evaluation protocol](https://github.com/open-feature/protocol) that may be of interest to you.

**Comment by Nikzz3** [comment]
Hi @beeme1mr,
Thanks for the clarification. With your explanation it makes sense. As mentioned in the documenation we will fetch all flag once and then do a local evaluation.

**Comment by beeme1mr** [comment]
Okay, great. Hopefully, that works well for you. We're happy to help if you run into any issues or limitations.
