### ISSUE TITLE
[BUG] Removing skipLibCheck throws an error

### ISSUE THREAD

**Issue by gogbog** [open-feature/js-sdk#845]
### Observed behavior

We have a project where we want to use web-sdk and we already have a provider. When we try to use sdk in the project without the `--skipLibCheck` it doesn't compile.

It throws the following error:

```
Could not find a declaration file for module 'events'. 'relative-path/angular-first/node_modules/events/events.js' implicitly has an 'any' type.

Try `npm i --save-dev @types/events` if it exists or add a new declaration (.d.ts) file containing `declare module 'events';` [plugin angular-compiler]
```

By installing `npm i --save-dev @types/events`, I'm getting the following error:

```
TS2709: Cannot use namespace 'EventEmitter' as a type. [plugin angular-compiler]
node_modules/@openfeature/web-sdk/dist/types.d.ts:110:37:
protected readonly eventEmitter: EventEmitter;
```

### Expected Behavior

There is no compile error, even tho the skipLibCheck is false.

### Steps to reproduce

1. Create a new angular project - `ng new angular-test`
2. Install open-feature SDK - `npm i @openfeature/web-sdk`
3. Import Open Feature SDK in some TS file - `import { OpenFeature } from '@openfeature/web-sdk'`
4. Switch SkipLibCheck in tsconfig.json to **FALSE**

**Comment by lukas-reining** [comment]
Hey @gogbog, thanks for submitting the issue.
I will have a look at this later.

**Comment by toddbaert** [comment]
@gogbog version `0.4.15` is released and @lukas-reining and I believe it should fix your issue, but please confirm and close if it does!

This new version also has the benefit for totaling 220kB instead of 250kB

**Comment by gogbog** [comment]
@toddbaert @lukas-reining Thanks for the fast response. Everything worked as expected. I'm closing the issue.
