### ISSUE TITLE
[BUG] Production NextJS build fails when a dependency uses the OpenFeature React or Web SDK

### ISSUE THREAD

**Issue by juanparadox** [open-feature/js-sdk#874]
### Observed behavior

I have a freshly made NextJS app (no extra config changes whatsoever, just what the `npx create-next-app@latest` command spits out with all of the default settings/selections in the CLI). I also have a Vite library that uses the OpenFeature React SDK. When the NextJS app has the Vite library as a dependency, the production build of the NextJS fails with a `TypeError: Cannot read properties of null (reading 'Symbol(@openfeature/web-sdk/api)')` error.

For whatever reason, when looking at the `next` bundled server code, the OpenFeature Web SDK code has `globalThis` replaced with `null` (which is what the error is complaining about). The TypeError is specifically happening here where `null` should be some variable which is set to `globalThis`:
```
static getInstance() {
                let t = null[nI];
                if (t)
                    return t;
                let n = new e;
                return null[nI] = n,
                n
            }
```

which seems to align with this source code: https://github.com/open-feature/js-sdk/blob/3546ba5e11351a6270f21e9ef24982e5674f677a/packages/client/src/open-feature.ts#L46

To be clear:
- a NextJS app that has OpenFeature SDK as a dependency work fine without issue. It is only when a dependency uses the OpenFeature SDK that the problem arises.
- this error does not occur when running `next dev` (the local development server)

### Expected Behavior

I would expect to be able to use any dependency which uses a React or Web OpenFeature SDK as expected without runtime or buildtime errors.

### Steps to reproduce

The following steps will go over creating the NextJS app and the Vite library. For the purposes of keeping this simple, we will use the OpenFeature Web SDK and not the React SDK since it is still experimental, though the issue also exists with the React SDK.

**Create the Vite library:**
1. Run `npm create vite@latest`
2. Use the following answers to the prompts:
```
✔ Project name: … vite-project
✔ Select a framework: › Vanilla
✔ Select a variant: › TypeScript
```
4. Go into the new project's directory and install the dependencies:
```
cd vite-project
npm install
```
5. Install Node typings `npm install -D @types/node`
6. Install OpenFeature Web SDK `npm install --save @openfeature/web-sdk`
7. Create a `vite.config.ts` Vite config file at the root of the project so that Vite build the library appropriately ([library config documentation](https://vitejs.dev/guide/build.html#library-mode))
```
import { resolve } from "path";
import { defineConfig } from "vite";

export default defineConfig({
  build: {
    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, "src/main.ts"),
      name: "MyProject",
      // the proper extensions will be added
      fileName: "my-project",
    },
  },
});

```
8. In the `src` directory, edit `main.ts` to export a function which sets an OpenFeature provider
```
import { OpenFeature } from "@openfeature/web-sdk";

export function start() {
  OpenFeature.setProvider({
    resolveBooleanEvaluation() {
      return {
        value: true,
      };
    },
    resolveStringEvaluation() {
      return {
        value: "",
      };
    },
    resolveNumberEvaluation() {
      return {
        value: 0,
      };
    },
    // @ts-expect-error There is a value mismatch with the type of T
    resolveObjectEvaluation() {
      return {
        value: "",
      };
    },
  });
}

```
9. Update the `package.json` to ensure the library can be imported correctly by other applications (in this case our NextJS app)
```
"files": [
    "dist"
  ],
  "main": "./dist/my-project.umd.cjs",
  "module": "./dist/my-project.js",
  "exports": {
    ".": {
      "import": "./dist/my-project.js",
      "require": "./dist/my-project.umd.cjs"
    }
  },
```
`package.json` should now look something like this:
```
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "files": [
    "dist"
  ],
  "main": "./dist/my-project.umd.cjs",
  "module": "./dist/my-project.js",
  "exports": {
    ".": {
      "import": "./dist/my-project.js",
      "require": "./dist/my-project.umd.cjs"
    }
  },
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@types/node": "^20.11.27",
    "typescript": "^5.2.2",
    "vite": "^5.1.6"
  },
  "dependencies": {
    "@openfeature/web-sdk": "^0.4.16"
  }
}

```

**Create the NextJS app:**
1. Run `npx create-next-app@latest` in the terminal (further instructions if needed are found [here](https://nextjs.org/docs/getting-started/installation) )
2. Use all of the default answers when prompted
3. Create a component at the root `component/OpenFeature.tsx`
```
"use client";
import { start } from "vite-project";

function OpenFeature() {
  start();
  return null;
}

export default OpenFeature;
```
4. Import the created component into `app/page.tsx` and render it as the first element within `<main>`
```
import Image from "next/image";
import styles from "./page.module.css";
import OpenFeature from "@/components/OpenFeature";

export default function Home() {
  return (
    <main className={styles.main}>
      <OpenFeature />
...
```

**NPM link the Vite library to the NextJS app:**
1. In the Vite library root, run `npm link`
2. In the NextJS app root, run `npm link vite-project`

Create a production NextJS build and serve it:
1. At the root of the NextJS app, run `npm run build`
2. Build fails with:
```
> my-app@0.1.0 build
> next build

   ▲ Next.js 14.1.3

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/5)  [=   ]TypeError: Cannot read properties of null (reading 'Symbol(@openfeature/web-sdk/api)')
    at e.getInstance (/Users/c596966/Development/my-app/.next/server/app/page.js:1:9356)
    at 6930 (/Users/c596966/Development/my-app/.next/server/app/page.js:1:12321)
    at t (/Users/c596966/Development/my-app/.next/server/webpack-runtime.js:1:127)
    at F (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94693)
    at j (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:93244)
    at rP (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33905)
    at nL (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62423)
    at nB (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nL (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'Symbol(@openfeature/web-sdk/api)')
    at e.getInstance (/Users/c596966/Development/my-app/.next/server/app/page.js:1:9356)
    at 6930 (/Users/c596966/Development/my-app/.next/server/app/page.js:1:12321)
    at t (/Users/c596966/Development/my-app/.next/server/webpack-runtime.js:1:127)
    at F (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94693)
    at j (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:93244)
    at rP (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33905)
    at nL (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62423)
    at nB (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nL (/Users/c596966/Development/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
 ✓ Generating static pages (5/5) 

> Export encountered errors on following paths:
        /page: /
```

**Comment by toddbaert** [comment]
Nice job @beeme1mr . Bundling would also actually lead to potential type issues and other nefarious errors like instanceof failing, if you compared exported instance from different libs that both bundled their own copy.

**Comment by juanparadox** [comment]
@beeme1mr Thank you! Problem solved 😄
