### ISSUE TITLE
[BUG] useXFlagValue not updating on ConfigurationChanged events

### ISSUE THREAD

**Issue by kyle-ssg** [open-feature/js-sdk#881]
### Observed behavior

I've implemented what I thought to be the final implementation of the [Flagsmith provider for OpenFeature](https://github.com/Flagsmith/js-sdk-contrib/pull/1/files#diff-7e037b1d1a96dec0437414d60c739aa873531e1b539e5c9d6e221615c3f6120dR72), we'll be reviewing the PR internally before submitting it to js-contrib. It works entirely as expected except for this scenario.

Essentially the flow is as follows

Consumer:

```
OpenFeature.setProvider(new FlagsmithProvider({
    environmentID: "env",
    cacheFlags:true
}));
```

Flow:

- Flagsmith SDK: gets flags from local storage, calls onChange 
- Open Feature Provider: gets [onChange event](https://github.com/Flagsmith/js-sdk-contrib/pull/1/files#diff-7e037b1d1a96dec0437414d60c739aa873531e1b539e5c9d6e221615c3f6120dR72)
   - Emits a Ready event
   - Emits a ConfigurationChanged event
   - Successfully evaluates with values based on local storage
- Flagsmith SDK: gets flags from server, calls onChange
- Open Feature Provider: gets [onChange event](https://github.com/Flagsmith/js-sdk-contrib/pull/1/files#diff-7e037b1d1a96dec0437414d60c739aa873531e1b539e5c9d6e221615c3f6120dR72)
   - Emits a Ready event
   - Emits a ConfigurationChanged event if the flags have indeed changed
   - Successfully evaluates with values based on flags from the server
- Flagsmith SDK: persists new flags in local storage

In a [non-react implementation](https://github.com/Flagsmith/flagsmith-js-examples/pull/9/files#diff-01c8a7f13863dbb394f17a4b3272701ff5cd7d6416248769748de6df25154a1cR42) this works perfectly when the the application listens to ProviderEvents.ConfigurationChanged and re-renders with new evaluated values.

### Expected Behavior

I think the React SDK only checks for evaluation updates after a contextChanged has been triggered, I'd expect it to respond to ConfigurationChanged events if the new evaluations don't equal previous evaluations. Reading the docs it does seem like both context and configuration changes should be triggering the hooks, from what I've seen it's just context doing it. 

If I trigger a context change via ``OpenFeature.setContext({...})`` the hooks do successfully update, e.g. [here](https://github.com/Flagsmith/flagsmith-js-examples/pull/9/files#diff-553fd540cc134c09dcd605974632732757703a6abd03e56fda1b8a4f5fd75ec7R8). Setting context goes through the exact same flow as the last 3 steps above. 

### Steps to reproduce

Initialise a provider update its state without context changing and asynchronously trigger a ConfigurationChanged event.

I've been able to validate that the config changed event in my reproduction did trigger and that ``OpenFeature.getClient().getNumberValue()`` returns a newer value than the hook.

<img width="675" alt="image" src="https://github.com/open-feature/js-sdk/assets/8608314/4c549b1d-c2ee-43f1-b6de-905694d04e15">

**Comment by kyle-ssg** [comment]
On testing this with multiple frameworks it seems I am only able to replicate this in an SSR context, I'll do some more digging and re-open if there's an issue.

**Comment by toddbaert** [comment]
@kyle-ssg I believe what you are describing is implemented in our react demo app [here](https://github.com/open-feature/react-test-app/blob/main/src/demos/FlagChangeDemo.tsx). Here, every 2 seconds we change the flags on the in-memory provider, which results in a re-render of the component based on the `ConfigurationChanged` event. I just tested it out and it seems to be working.

Can we sanity check a couple things?

- what version of the react SDK are you using?
  - have you manually installed `@openfeature/core` or `@openfeature/web-sdk`? They should be installed automatically as peers, so they shouldn't be in your package.json
- does the `domain` of the client match the domain of the provider?

**Comment by kyle-ssg** [comment]
Versions: 
```
    "@openfeature/react-sdk": "^0.2.2-experimental",
    "@openfeature/web-sdk": "^1.0.0",
```

I'll remove web-sdk, I didn't realise it'd be a peer dependency.

**Comment by kyle-ssg** [comment]
Hey @toddbaert thanks for getting back to me

Versions: 
```
    "@openfeature/react-sdk": "^0.2.2-experimental",
    "@openfeature/web-sdk": "^1.0.0",
```

I'll remove web-sdk, I didn't realise it'd be a peer dependency. As for the domains, the provider is set without one so it's always the default. 

As for replication it may be a bit difficult since the provider isn't published yet. I'll look at why the sample app works and mine doesn't. I do know that:

- this.events.emit(ProviderEvents.ConfigurationChanged) is called
- ConfigurationChanged is being emitted
- getNumberValue is resolving with a new value

There must be something else under the hood with my provider implementation that causes the hook not to re-evaluate.

**Comment by kyle-ssg** [comment]
Ok yeah my last point is the issue, there's a race condition. 

- App: First render with default flags useNumberFlagValue(...)=>12
- Provider: calls back with configuration change as a result of reading cache (pretty much immediate for web)
- Open Feature - [initialises configuration changed handler](https://github.com/open-feature/js-sdk/blob/main/packages/react/src/use-feature-flag.ts#L195) ever so slightly too late since it's in useEffect

I'm wondering whether I can avoid this issue Flagsmith's SDK side / whether configchanges would beat useEffect in other scenarios / providers, I'm not sure how long the asynchronous the delay for useEffects could be. 

Our web cache can technically be synchronous, we just make it async to genericise other platform storage e.g. react native.

**Comment by toddbaert** [comment]
Ahh very interesting.

OK if I'm understanding correctly, that means that you are basically missing only 1 initial event in your test app due to this race condition; if you got additional changes from the Flagsmith backend, you would see those, yes?

**Comment by toddbaert** [comment]
If this first event is always just a result of reading from cache, maybe it's worth doing that read from cache in the `initialize`, which will mean we have read the cached state before anything is rendered.

Then, only subsequent changes coming from the network will cause further change events, long after all the handlers are set up.

**Comment by kyle-ssg** [comment]
> Ahh very interesting.
> 
> OK if I'm understanding correctly, that means that you are basically missing only 1 initial event in your test app due to this race condition; if you got additional changes from the Flagsmith backend, you would see those, yes?

Yeah exactly if a change event occurred 50ms later we'd get a re-render due to the hook.




> If this first event is always just a result of reading from cache, maybe it's worth doing that read from cache in the `initialize`, which will mean we have read the cached state before anything is rendered (seems like not a bad idea since this is guaranteed to be fast).
> 
> Then, only subsequent changes coming from the network ("real" change events) will cause further change events, long after all the handlers are set up.

Yeah I think maybe you're right, default flags can probably hold off on our end until cache is evaluated.

**Comment by kyle-ssg** [comment]
I can confirm that moving Flagsmith to synchronous cache fixes the issue I observed.

I think this can be closed, but I'm not 100% sure. Technically if a Provider's init is very fast I think this could still be replicable?

**Comment by kyle-ssg** [comment]
Ok it seems in that case the synchronous state above, it can be resolved by setting this the Provider constructor, not on initialize. 

I think I'll close this as all paths lead to being able to resolve this in providers.

**Comment by toddbaert** [comment]
Thanks @kyle-ssg , good to have this discussion for posterity and education anyway.
