### ISSUE TITLE
[BUG] React SDK suspends after useEffect rather than during a component's first render, causing components to flicker

### ISSUE THREAD

**Issue by tjosepo** [open-feature/js-sdk#920]
### Observed behavior

The current implementation of Suspense in the React SDK seems kind of buggy.

A component is meant to suspend **during** rendering, but the React SDK makes the component suspend **after** the inital render, after running useEffect. 

This not only breaks React APIs like `startTransition`, but it leads to a noticeable "blinking" effect.

![open-feature-suspense-bug](https://github.com/open-feature/js-sdk/assets/44372776/b57211ef-9cbb-4257-bddb-6f4b481359b1)

So, the current behavior seems to be:

1. Component renders once, very quickly, with invalid values, while the Client is `NOT_READY`.
2. useEffect runs, sets the state to a function that throws a promise.
2. Component rerenders and suspend (because it suspends in the second render, it's too late for startTransition to work now ❌)
3. Component renders again, once the Client is `READY`.

### Expected Behavior

A component should suspend immediatly during its first render, not in a second render after the effects have fired.

### Steps to reproduce

**CodeSandbox:** https://codesandbox.io/embed/openfeature-suspense-bug-5j7yll?fontsize=14&hidenavigation=1&theme=dark

The test in [/packages/react/test/provider.spec.tsx](https://github.com/open-feature/js-sdk/blob/86a9230addb8b7a0bb34ca7ef6d69b27209128f2/packages/react/test/provider.spec.tsx#L96C9-L98C66) show a false positive, because React Testing Library only shows the state of the DOM **after** the effects have run. 

To make sure that the `'👎'` truly never appears, we can add a mutable variable that tracks wether or not the component suspend properly. If the component suspends properly, `isReady` will never be `false`, because `useWhenProviderReady` should suspend before the function completes.

Here is a modified version of the `'should suspend until ready and then return provider status'` test that catches the component not suspending properly:

```js
it('should suspend until ready and then return provider status', async () => {
  OpenFeature.setProvider(SUSPENSE_ON, suspendingProvider());

  let renderedWhileNotReady = false;

  function Component() {
    const isReady = useWhenProviderReady();

    if (!isReady) {
      renderedWhileNotReady = true;
    }

    return (
      <>
        <div>{isReady ? '👍' : '👎'}</div>
      </>
    );
  }

  render(
    <OpenFeatureProvider domain={SUSPENSE_ON}>
      <React.Suspense fallback={<div>{FALLBACK}</div>}>
        <Component></Component>
      </React.Suspense>
    </OpenFeatureProvider>,
  );


  // should see fallback initially
  expect(renderedWhileNotReady).toBe(false);
  expect(screen.queryByText('👎')).not.toBeInTheDocument();
  expect(screen.queryByText(FALLBACK)).toBeInTheDocument();
  // eventually we should the value
  await waitFor(() => expect(screen.queryByText('👍')).toBeVisible(), { timeout: DELAY * 2 });
});
```

**Comment by tjosepo** [comment]
One question I have:

- Is there a reason why Suspense was implemented by throwing a promise in a `set` function, rather than throwing the promise during the rendering phase of the component?

I was not aware of this method of triggering suspense.

Should we consider reimplementing suspense in a way that aligns with the upcoming [use() hook](https://react.dev/reference/react/use)?

**Comment by toddbaert** [comment]
Hey @tjosepo . Thanks for the report and reproduction. You're right about this. I have a fix locally, but I want to check a few other things out to be sure it's working as expected. 

> Is there a reason why Suspense was implemented by throwing a promise in an updater function, rather than throwing the promise during the rendering phase of the component?
> 
> I was not aware of this method of triggering suspense, so I might be missing some context here.

Well, in our case there is no component, only hooks, but we can throw a promise from the hook body immediately (not in the updater function `useEffect`), which is the approach I've taken in my fix... maybe that's what you meant?

Stay tuned, I'll have a fix soon I think and add you to the PR.

**Comment by tjosepo** [comment]
Great!

I opened a draft PR with a potential fix, that also supports `startTransition()`.

Feel free to dismiss the PR if you already have a fix.

**Comment by toddbaert** [comment]
> Great!
> 
> I opened a draft PR with a potential fix, that also supports `startTransition()`.
> 
> Feel free to dismiss the PR if you already have a fix.

No, no, no, you've done a great job. We've basically done the same thing but so far your code looks clearer. Please continue, I will happily accept your PR.

**Comment by toddbaert** [comment]
I'm assigning you for now, if you can't finish, let me know and I will take over.
