### ISSUE TITLE
[BUG] Outdated pinned peerDependency from web-sdk to core

### ISSUE THREAD

**Issue by andreas-karlsson** [open-feature/js-sdk#963]
### Observed behavior

The web-sdk has been released with "lower compilation target to es2015", but the peer dependency to core is still pinned to `1.2.0` which has compilation target `es2022`. Was it supposed to be updated? Should the peer dependency to core maybe use caret? Technically in semantic versioning, updating a peer dependency is a breaking change. If a caret range is used instead, I would also suggest that the devDependency is pinned to the lowest version of that range. This way it will be obvious during development if there is a need to bump the peer dependency.

**Comment by toddbaert** [comment]
We have automation that is supposed to catch exactly this issue, but I think either something went wrong and the CI didn't block me, or I overrode it. I can see where the check failed and the release PR was merged anyway :cry:
