### ISSUE TITLE
[FEATURE] React SDK: Provide hook to set relevant context "`useContextMutator`"

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#968]
### Background

The `OpenFeatureProvider` React context provider binds an OpenFeature client to a React Context. Components within that boundary use the associated client for evaluations, etc. The client can be associated with a domain (see https://github.com/open-feature/js-sdk/blob/main/packages/react/README.md#multiple-providers-and-domains and https://github.com/open-feature/js-sdk/blob/main/packages/client/README.md#domains)

We do not currently have a hook that makes it easy to update this context. It's necessary to use the global object to do this. We should add a hook that allows the correct context for the enclosed scope to be set.

For example, this current implementation:

```tsx
<OpenFeatureProvider domain={'my-domain'}>
  <button
    onClick={() => {
      OpenFeature.setContext('my-domain', updatedContext);
    }}
  >
      click here
  </button>
</OpenFeatureProvider>
```

Could be instead be:

```tsx
<OpenFeatureProvider domain={'my-domain'}>
  <button
    onClick={() => {
      mutateContext(updatedContext); // function returned by new hook, associated with the 'my-domain' domain
    }}
  >
      click here
  </button>
</OpenFeatureProvider>
```

This would make things easier for users, and fit better into react idioms. Please test your solution but using it in the sample react app [here](https://github.com/open-feature/react-test-app/blob/85b48aafc50eae2d6dab1e24189b8e4c0fd44e08/src/demos/ContextChangeDemo.tsx#L82-L84).

### Requirements

- new hook added which returns function to mutate context (please come up with a reasonable name for the hook and returned function)
- associated tests
- associated README updates
- React demo updated [here](https://github.com/open-feature/react-test-app/blob/85b48aafc50eae2d6dab1e24189b8e4c0fd44e08/src/demos/ContextChangeDemo.tsx#L82-L84)
- returned func(s) should probably be async

### Additional Considerations

I'd love to see considerations from the implementor on the following:

- should we export a couple different functions? `setContext`, `mergeContext` etc, which merge the context?
- should we ignore changes if the reference hasn't changed?

**Comment by wichopy** [comment]
volunteer to tackle this one

**Comment by wichopy** [comment]
@toddbaert is there tooling to pull in the build with my changes in js sdk and use it with react test app project?

I was able to locally test manually using yalc but was wondering how you would go about it.

**Comment by beeme1mr** [comment]
Yalc is probably the easier way to try this in the test app.
