### ISSUE TITLE
[BUG] peer dependencies not installed we running npm install --legacy-peer-deps

### ISSUE THREAD

**Issue by Smarmellata** [open-feature/js-sdk#996]
### Observed behavior

I am using this web sdk in an angular app that need --legacy-peer-deps to correctly run npm install.
In this situation if i install the web sdk package using --legacy-peer-deps to, i get errors in some imports of some interfaces and classes of my provider. looking in my node modules infact i can see that "core" folder is not listed under the @openfeature folder.
I also tried to install manually the core package (also running the command with --legacy-peer-deps) and also in this case i have errors in my code about some imports.

**Comment by beeme1mr** [comment]
Hi @Smarmellata, you'll need to manually install and maintain "core" if you're using --legacy-peer-deps. What errors are you seeing when you manually install it? What versions are "web" and "core" are you using?

It's worth mentioning that the [NPM docs](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps) mention that the `use of legacy-peer-deps is not recommended, as it will not enforce the peerDependencies contract that meta-dependencies may rely on.`

**Comment by Smarmellata** [comment]
Hi @beeme1mr very thanks for the fast response!
I was kind of thinking that the not presence of "core" when installing with --legacy-peer-deps was intended, but i got confused when i got the same errors while compiling my app after the manual installation of core.

about the version of web and core, i am using web-sdk at latest version `"@openfeature/web-sdk": "^1.2.3",` and trying to install it manually i was using the latest `"@openfeature/core": "^1.4.0",` , but then i downgraded to 1.3.0 checking the package json of the web-sdk in the node modules.

I was getting errors on imports, but today starting with a fresh mind i was able to solve the issue in this way:
- deleted package lock json
- added on package json dependency for web sdk latest version and core latest version
- delete node modules
- run npm install --legecy-peer-deps

this solved all the errors.

thanks again for support and fast response.
